Modified action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -38,10 +38,10 @@ runs:
         - name: Checkout repository
           uses: actions/checkout@v4
 
-        - name: Use Python 3.8.x
-          uses: actions/setup-python@v2.2.1
+        - name: Use Python 3.12
+          uses: actions/setup-python@v5
           with:
-              python-version: 3.8.x
+              python-version: 3.12
 
         - name: Create and populate connections.toml
           shell: bash
@@ -74,21 +74,25 @@ runs:
           run: |
               echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
               python --version
+              echo "Step 1: Installing schemachange"
               pip install schemachange
 
         - name: "Deploying Schemachange on database: ${{ inputs.SF_DATABASE }}"
           shell: bash
           run: |
-              echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
-              python --version
-              echo "Step 1: Installing schemachange"
-              pip install schemachange
-
               echo "Step 2: Deploying schemachange on database: ${{ inputs.SF_DATABASE }}"
               schemachange \
-                --root-folder $GITHUB_WORKSPACE/${{ inputs.LOCATION_OF_DDL_SCRIPTS }} \
+                --root-folder ./${{ inputs.LOCATION_OF_DDL_SCRIPTS }} \
                 --connections-file-path ./connections.toml \
                 --connection-name default \
                 --change-history-table ${{ inputs.SF_DATABASE }}.SCHEMACHANGE.CHANGE_HISTORY \
                 --create-change-history-table \
-                ${{ inputs.DRY_RUN }}
+                ${{ inputs.DRY_RUN }} \
+                --verbose 
+                RESULT=$?
+
+                if [ $RESULT -eq 0 ]; then
+                    echo "Deployment Completed!"
+                else
+                    echo "Deployment Failed."
+                fi   
